{% set version = "8.1.1" %}

package:
  name: "bftools"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
  sha256: 338cade0a24c989b398993f5a4ef013e79d54bb5d8b133356755db2243dc630e

requirements:
  run:
  - bftools-libs={{ version }}-{{ PKG_BUILDNUM }}
  - openjdk

test:
  commands:
  - bfconvert a.fake a.tiff
  - domainlist
  - formatlist
    # - ijview
  - mkfake test
  - showinf -nopix a.fake
  - tiffcomment a.tiff
    # - xmlindent
    # - xmlvalid

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
