{% set version = "6.7.0" %}

package:
  name: "bftools"
  version: "{{ version }}"

build:
  number: 0

source:
  url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
  sha256: 7c013b23529d61280e04c3dd312401d7b71fb5892f5e7870f87d37bab5f3988f

requirements:
  run:
  - bftools-libs={{ version }}-{{ PKG_BUILDNUM }}
  - openjdk

test:
  commands:
  - bfconvert a.fake a.tiff
  - domainlist
  - formatlist
    # - ijview
  - mkfake test
  - showinf -nopix a.fake
  - tiffcomment a.tiff
    # - xmlindent
    # - xmlvalid

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
