{% set version = "6.12.0" %}

package:
  name: "bftools-libs"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
  sha256: 5872db401a6f746e162af8b5b762502d03e5c7db80d97ba3b9fd9175da0ae69c

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools libraries
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
