{% set version = "8.0.0" %}

package:
  name: "bftools-libs"
  version: "{{ version }}"

build:
  number: 0
  noarch: generic

source:
  url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
  sha256: 46c7c53595a2491adc76dc3b7d4089689e5c3817a9bb549a632d08ef137438e7

extra:
  recipe-maintainers:
  - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools libraries
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
