{% set version = "6.6.0" %}

package:
  name: "bftools-libs"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

build:
  number: 0
  noarch: generic

source:
  url: https://downloads.openmicroscopy.org/bio-formats/{{ version }}/artifacts/bftools.zip
  sha256: d13553047ac552327107e029a077e32b48a7e0f7e028cf4c04d81539f2f56a21

extra:
  recipe-maintainers:
    - ome

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Bio-Formats command line tools libraries
  doc_url: https://docs.openmicroscopy.org/bio-formats/latest/users/comlinetools/index.html
  dev_url: https://github.com/ome/bioformats
