name: Conda

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true

      - name: Set conda-bld output folder to make it easier to find artifacts
        id: condablddir
        # On Windows /conda-bld and \\conda-bld work here but fail later
        # c:\\conda-bld seems to work.... for now
        run: |
          if [ ${{ matrix.os }} = windows-latest ]; then
            echo "condabld=c:\\conda-bld" >> $GITHUB_OUTPUT
          else
            echo "condabld=$HOME/conda-bld" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - run: |
          conda --version
          echo "${{ steps.condablddir.outputs.condabld }}"
          mkdir ${{ steps.condablddir.outputs.condabld }}
          conda config --set conda_build.output_folder ${{ steps.condablddir.outputs.condabld }}
          conda config --set channel_priority disabled

      - name: Checkout
        uses: actions/checkout@v4
      - name: Install conda build
        run: conda install -y -q conda-build conda-verify

      - name: Build bftools-libs
        run: conda build bftools-libs
        shell: bash -el {0}
      - name: Build bftools
        run: conda build bftools
        shell: bash -el {0}
      
      - run: ls -R "${{ steps.condablddir.outputs.condabld }}"
      # We want
      # - bftools-libs noarch from one job
      # - bftools *-64 from all jobs

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-noarch
          path: "${{ steps.condablddir.outputs.condabld }}/noarch/bftools-libs-*"
          if-no-files-found: error
        if: startsWith(matrix.os, 'ubuntu')
      - uses: actions/upload-artifact@v4
        with:
          # {linux,osx,win}-64
          name: artifact-${{ matrix.os }}-64
          path: "${{ steps.condablddir.outputs.condabld }}/*-64/bftools-*"
          if-no-files-found: error

  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:

      - name: setup-conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: defaults
          auto-update-conda: true
          auto-activate-base: true
      - run: conda install -y -q anaconda-client

      - name: Download artifacts from build
        uses: actions/download-artifact@v3
      - name: List artifacts
        run: ls -R

      - name: Upload to Anaconda Cloud
        run: |
          anaconda whoami
          for f in artifact*/bftools* artifact*/*/bftools*; do
            anaconda upload --user ${ANACONDA_USER} $f
          done
        env:
          ANACONDA_USER: ${{ secrets.ANACONDA_USER }}
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
