name: VersionBump

on:
  schedule:
    - cron: "* 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: install scc
        run: |
          pip install scc
      - name: Update version
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          scc bump-version-conda
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
